// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// const awsmobile = {
//     "aws_project_region": "us-west-2",
//     "aws_appsync_graphqlEndpoint": "https://tsahf7vqeng6thutuueaanzylq.appsync-api.us-west-2.amazonaws.com/graphql",
//     "aws_appsync_region": "us-west-2",
//     "aws_appsync_authenticationType": "API_KEY",
//     "aws_appsync_apiKey": "da2-youeb2krl5gvlm4odlnj6h44jm",
//     "aws_content_delivery_bucket": "newimpactprojectapi-devtwo",
//     "aws_content_delivery_bucket_region": "us-west-2",
//     "aws_content_delivery_url": "https://d1jfog88m7gtu9.cloudfront.net"
// };


const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://a4kfqfeqkfgxhaad2777qxhiy4.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dq52cxdnxzcx7pyuqfjdswijkm",
    "aws_content_delivery_bucket": "newbucketdata-newbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "https://di29v87uyt67h.cloudfront.netp"
};

export default awsmobile;
